// async function throwError() {
// 	throw new Error("Error thrown");
// }

// async function throwErrorChain() {
// 	return 2;
// }

// async function consumingError() {
// 	try {
// 		a = await throwErrorChain();
// 		console.log(a);
// 	} catch {}
// }

// consumingError().catch();

if (null.length) {
	console.log("Yes");
} else {
	console.log("No");
}
